USE `payment_system`;
DROP TABLE `TRANSACTION_ITEMS`;
DROP TABLE `TRANSACTIONS`;
DROP TABLE `CREDIT_PAYMENT_METHOD`;
DROP TABLE `COUPON_PAYMENT_METHOD`;
DROP TABLE `CASH_PAYMENT_METHOD`;
DROP TABLE `PRODUCTS`;
DROP TABLE `DEVICES`;
DROP TABLE `FIRMWARE`;
DROP TABLE `MODEL`;
DROP TABLE `SHOPS`;
DROP TABLE `MERCHANTS`;

