/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.InetSocketAddress;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;

public class App {

  public static void main(String[] args) {
    try {
      final HttpServer server = HttpServer.create(new InetSocketAddress(4478), 0);

      server.createContext("/receive", new HttpHandler() {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
          // Notify that an user has connected
          System.out.println("A new user connected from: " + exchange.getRemoteAddress());

          // We just need the body
          InputStreamReader isr = new InputStreamReader(exchange.getRequestBody());
          BufferedReader br = new BufferedReader(isr);
          String line = br.readLine();
          String fileName = "";
          String reportContent = "";
          while (line != null) {
            reportContent += line + "\n";
            // do line operations
            if (line.contains("reportHour")) {
              String delims = "<[^>]*>";
              fileName = line.split(delims)[2];
            }
            // read next line
            line = br.readLine();
          }
          File reportFile = new File(fileName + ".txt");
          if (reportFile.createNewFile()) {
            FileWriter myWriter = new FileWriter(reportFile);
            myWriter.write(reportContent);
            myWriter.close();
          }

          String response = "Success!";
          exchange.sendResponseHeaders(200, response.getBytes().length);
          exchange.getResponseBody().write(response.getBytes());
          exchange.getResponseBody().close();
        }
      });
      server.start();
      System.out.println("Listening for connection on : " + server.getAddress());
    } catch (IOException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
  }
}
