/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.InetSocketAddress;
import java.util.Arrays;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;

public class App {

  public static void main(String[] args) {
    try {
      final HttpServer server = HttpServer.create(new InetSocketAddress(4478), 0);
      server.createContext("/receive", new HttpHandler() {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
          // We just need the body
          InputStreamReader isr = new InputStreamReader(exchange.getRequestBody());
          BufferedReader br = new BufferedReader(isr);
          String line = br.readLine();
          while (!line.isEmpty()) {
            // do line operations
            if (line.contains("reportHour")) {
              String delims = "<[^>]*>";
              System.out.println(line.split(delims)[2]);
              return;
            }
            // read next line
            line = br.readLine();
          }
          exchange.sendResponseHeaders(200, 0);
          exchange.getResponseBody().close();

        }
      });
      server.start();
      System.out.println("Listening for connection on : " + server.getAddress());
    } catch (IOException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
  }
}
