PRAGMA foreign_keys = OFF;

DELETE FROM TRANSACTION_ITEMS;
DELETE FROM CASH_PAYMENT_METHOD;
DELETE FROM COUPON_PAYMENT_METHOD;
DELETE FROM CREDIT_PAYMENT_METHOD;
DELETE FROM TRANSACTIONS;
DELETE FROM DEVICES;
DELETE FROM FIRMWARE;
DELETE FROM MODEL;
DELETE FROM SHOPS;
DELETE FROM MERCHANTS;
DELETE FROM PRODUCTS;
DELETE FROM USERS;

PRAGMA foreign_keys = ON;

