PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS TRANSACTION_ITEMS;
DROP TABLE IF EXISTS CREDIT_PAYMENT_METHOD;
DROP TABLE IF EXISTS COUPON_PAYMENT_METHOD;
DROP TABLE IF EXISTS CASH_PAYMENT_METHOD;
DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS DEVICES;
DROP TABLE IF EXISTS MODEL;
DROP TABLE IF EXISTS FIRMWARE;
DROP TABLE IF EXISTS SHOPS;
DROP TABLE IF EXISTS MERCHANTS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS USERS;

PRAGMA foreign_keys = ON;
